from adjudicate_physics import *
id='psf-2024-proletno-9';t,d,c=start(id,'agent__sonnet');p1,p2,p3=d['problems'];d['paper']['held']['from']='2024-03-08';d['paper']['held']['to']='2024-03-10';p1['statement']='Задача 1.1.';p3['statement']='Задача 3.1.'
for p in d['problems']:p['points']=None
for f,b,doc in [(p1['figures'][0],[667,185,892,283],'problems'),(p1['solution']['figures'][0],[670,281,891,371],'solutions'),(p2['figures'][0],[716,469,897,578],'problems')]:f['tx']={'document':doc,'page':1,'bbox':b}
s=[defect('/paper/held','metadata','Human-readable dates fail required ISO YYYY-MM-DD schema format.'),defect('/problems/0/statement','schema','Empty top-level statements on problems1 and3 violate validator; printed subtask headings can serve as main label.' )]
h=[defect('/problems/0/parts/2/statement','omission','Omits printed atmospheric-pressure, water expansion, g and ρ paragraph.','critical'),defect('/paper/roundType','metadata','This is a theory paper, not test; checker suggested competition is not valid enum.'),defect('/problems/0/solution/figures','figure','Water/air-filled cylinders solution diagram absent.','critical'),defect('/problems/0/statement','reworded','Invents Задача с подчасти. for groups1 and3.' ,'minor'),defect('/problems/0/solution/statement','reworded','Source скачени съдове becomes свързани съдове.','minor'),defect('/paper/totalPoints','points','30 total and multiple group/subpart totals are inferred; source prints only subquestion scores.','minor')]
g=[defect('/problems/2/parts/0/statement','wrong-value','Printed first fall time t₁; candidate t.','critical'),defect('/problems/2/parts/1/statement','reworded','Repeatedly substitutes асаньор for printed асансьор, also in solutions.'),defect('/problems/1/solution/statement','formula','Rₓ bound and substitution must be √(aℰ/2), candidate √(aℰ)/2. Answer also wrong.','critical'),defect('/problems/0/statement','schema','Empty top-level statements for groups1 and3.'),defect('/problems/0/parts/1/figures','schema','parts[].figures is unsupported field.'),defect('/problems/0/parts/4','reworded','Treats unlabeled Приемете paragraph as invented separate subquestion.','minor'),defect('/problems/0/solution/statement','reworded','изотермно→изотермично, две равенства→два равенства, Физичен→Физически.','minor'),defect('/problems/2/solution/statement','reworded','десните→дясните, две→два, равноускорително→равномерно ускорено; subscript п becomes Latin n.','minor')]
for cand,arr in zip(t['candidates'],[h,s,g]):
 for cr in cand['crops']:arr.append(defect(cr['path'],'figure','Actual crop clips needed diagram elements or includes surrounding body text. Corrected full-page measured region recorded in gold.','critical'))
decisions={'agent__haiku__for-zai__glm-5.3-flash.json':[(True,'Clearly printed t₁ on problems page1.'),(True,'Printed асансьор throughout. Suggested электромотор would itself be wrong; source електромотор.'),(True,'Crop contains body text and clips h at right. More severe than checker says.'),(True,'Actual circuit crop contains extensive body text.'),(True,'Solution crop omits left cylinder/height h, in addition to body text; critical, not minor.')], 'zai__glm-5.3-flash__for-agent__haiku.json':[(True,'Printed common assumptions wholly absent.'),(True,'Actual crop not merely at risk: extensive text and upper cylinder clipping.'),(True,'test is wrong for derivations; correct enum theory, not suggested competition.'),(False,'Printed t₁ is readable; candidate t₁ is correct. Informational speculation is not defect.'),(True,'Placeholder sentence is not printed; minor addition.')], 'zai__glm-5.3-flash__for-agent__sonnet.json':[(False,'Correct preservation of printed full stop is not a defect.')]}
finish(t,d,c,{'agent__haiku.figs.view.json':h,'agent__sonnet.figs.view.json':s,'zai__glm-5.3-flash.figs.view.json':g},decisions,'All readers fail figure extraction on this paper. Sonnet otherwise transcribes the mathematics faithfully but has invalid date fields and two empty statements; GLM also changes the resistance bound and time subscript. GLM pass on Sonnet misses all three clipped figure crops.','All three pages and eight candidate crops inspected. Corrected boxes measured from source. Printed heading used for otherwise empty grouped statement; complete subtask content remains in parts. Source punctuation (full stop at end of 1.2Б and2В) preserved; decimal dots in printed scores preserved.')
