from adjudicate_physics import *
id='psf-2006-proletno-sp'; t,d,c=start(id,'agent__sonnet')
p1,p2,p3=d['problems']
d['paper']['title']='МИНИСТЕРСТВО НА ОБРАЗОВАНИЕТО И НАУКАТА\nНАЦИОНАЛНО ПРОЛЕТНО СЪСТЕЗАНИЕ ПО ФИЗИКА\nПловдив, 17 – 19.03.2006 г.\nСпециална тема'
for p in d['problems']: p['points']=None
p1['parts'][2]['statement']=p1['parts'][2]['statement'].replace(r'2{,}0\times10',r'2{,}0\cdot10')
p2['statement']=p2['statement'].replace(r'1{,}60\times10',r'1{,}60\cdot10').replace(r'6{,}64\times10',r'6{,}64\cdot10')
p2['parts'][2]['statement']=p2['parts'][2]['statement'].replace('$e$. **[2 т]**','$e$. . **[2 т]**')
p2['solution']['statement']=p2['solution']['statement'].replace('ограждда','огражда').replace('дясната ръка','дяната ръка').replace('води до индуциране','воде до индуциране').replace('с големина $q$ от','с големина , $q$ от').replace(r'6{,}64\times10',r'6{,}64\cdot10').replace(r'4\pi\times10',r'4\cdot\pi\cdot10').replace(r'1{,}60\times10',r'1{,}60\cdot10').replace(r'1{,}65\times10',r'1{,}65\cdot10')
p2['parts'][2]['answer']={'kind':'expression','latex':r'\mathcal{E}=-\dfrac{\mu_0 g a^2v}{2(z^2+a^2)^{3/2}},\qquad Q=\dfrac{3\pi h^2v}{128e^2aR}','note':'В решението е отпечатано g; в условието зарядът е означен g_e.'}
p3['parts'][2]['answer']={'kind':'text','value':'P₂ = 63 W. Консумираната мощност от нагревателя намалява 2 пъти; консумираната от термопомпата мощност намалява 4 пъти.'}
for p in d['problems']: p['solution']['statement']='**Задача '+str(p['number'])+'. '+p['title']+'**\n\n'+p['solution']['statement']
p1['solution']['statement']='Национално пролетно състезание по физика\nПловдив, 17 – 19.03.2006 г.\nПримерни решения на задачите от Специалната тема\n\n'+p1['solution']['statement']
boxes={'p1-fig1':[560,192,847,326], 'p1-sol-fig1':[143,680,428,813], 'p1-sol-fig2':[300,375,860,715], 'p2-fig1':[192,800,503,887], 'p2-fig2':[504,792,877,890], 'p2-fig3':[597,146,750,219], 'p2-sol-fig1':[546,88,920,185], 'p2-sol-fig2':[536,405,909,541], 'p3-fig1':[543,318,864,414], 'p3-fig2':[459,793,669,925], 'p3-fig3':[726,786,839,892]}
for p in d['problems']:
 for f in p.get('figures',[])+p.get('solution',{}).get('figures',[]):
  f['tx']={'document':f['tx']['document'],'page':f['tx']['page'],'bbox':boxes[f['id']]}
# All defects below were checked against the images, not inferred from candidate agreement.
h=[defect('/problems/1/parts/2/points','points','Part в has printed bullet scores 2 and 2; candidate assigns 6. Null aggregate retained in gold, bullet scores verbatim.','critical'),defect('/problems/2/parts/2/points','points','Part в has printed bullet scores 3 and 1; candidate assigns 2.','critical'),defect('/problems/1/parts/1/statement','reworded','Printed Като използвате; candidate Бъд като използвате.'),defect('/problems/2/parts','reworded','Systematic име instead of има and външни стена instead of външна стена.'),defect('/problems/0/solution/statement','omission','Omits the full 15-row numerical table and multiple printed graph/table scoring conditions.'),defect('/problems/0/solution/statement','formula','Eq (7) printed −T tg α; candidate −Tgα removes the tangent operator.','critical'),defect('/problems/0/solution/statement','reworded','Drops/rewords the small-angle justification and garbles милиметрова, ъглополовяща, откъдето.'),defect('/problems/1/solution/statement','omission','Collapses two alternative derivations, omits second variant equations (14)–(17) and full numeric substitution (9).'),defect('/problems/1/solution/statement','formula','Eq (13) numerator printed μ₀ga²v; candidate uses μ₀g_e²v. Eq (19) printed a⁴v; candidate a²v².','critical'),defect('/problems/1/solution/statement','points','Adds [1 т] to equations (5) and (7), where no score is printed.'),defect('/problems/2/solution/statement','omission','Omits full formulas (3), (8), (11), (12), (13), retaining several bare numerical results.'),defect('/problems/2/solution/statement','reworded','Last explanation is corrupted into Колорgermania мощност...','critical'),defect('/problems/1/figures','figure','Omits the source cone-angle diagram on problems page 3 and both solution diagrams on solutions page 4.','critical')]
g=[defect('/problems/0/statement','omission','Omits the complete Упътване block, including gravity assumption, wave speed equation (3), and graph-paper hand-in requirement.'),defect('/problems/1/statement','omission','Omits all three fundamental constants and the page-3 cone-angle/integral hints.'),defect('/problems/1/figures','figure','Omits the cone-angle hint figure on problems page 3.','critical'),defect('/problems/1/statement','reworded','Source typo фундаменталин is silently corrected to фундаментален.','minor'),defect('/problems/1/parts/1/statement','reworded','Printed целочислено becomes цялочислено.','minor'),defect('/problems/1/solution/statement','formula','Numeric substitution (9) has printed product 2·4·π, candidate decimal 2,4·π; numerical equality no longer matches.','critical'),defect('/problems/2/solution/statement','formula','Window-power subscript printed п; candidate н.'),defect('/problems/0/solution/statement','reworded','Changes decimal dots in the entire numerical table and x≈0.86 to commas; source преобразования becomes преобразувания and drops е before ъглополовяща.','minor'),defect('/problems/1/solution/statement','reworded','Printed магнитния кондензатор becomes магнитни кондензатор; заместим becomes заместваме; отчели becomes отчитали.','minor'),defect('/problems/2/statement','reworded','Printed нарича becomes наича.','minor'),defect('/problems/2/solution/statement','reworded','Printed слоя въздух becomes слой въздух.','minor'),defect('/problems','omission','Omits most printed equation numbers despite referring to those equation numbers in prose.')]
s=[defect('/problems/1/solution/statement','reworded','Printed огражда becomes ограждда; source errors дяната and воде are silently corrected to дясната and води.','minor'),defect('/problems/1/solution/statement','reworded','Omits printed stray comma before q in На свободен заряд с големина , q; small source punctuation differences.','minor'),defect('/problems/1/parts/2/answer','omission','Final printed EMF and heat results not represented in answer despite supplied solution.'),defect('/problems/2/parts/2/answer','omission','Final printed 63 W and reduction factors 2 and 4 absent from answer despite supplied solution.')]
for df in [h,g,s]: df.append(defect('/problems/*/points','points','Problem totals are inferred, not separately printed. Gold leaves problem totals null.','minor'))
for df in [h,g,s]: df.append(defect('/paper/title','omission','Full printed masthead and special-topic designation are abbreviated in paper title.','minor'))
# Actual crops, individually inspected. A clipped label or body-text inclusion is critical by contract.
for x in t['candidates'][0]['crops']:
 desc={'p1-fig1':'Swallows large sections of problem text.','p1-sol-fig1':'Clips the right half of the diagram, forces, angle and y label.','p1-sol-fig2':'Swallows body text and table; clips graph bottom/x label.','p2-fig1':'Only body text, no capacitor diagram.','p2-fig2':'Only body text, no ring diagram.','p3-fig1':'Wrong figure: p2 cone hint plus body text, not thermal layer.','p3-fig2':'Only body text, not wall diagram.','p3-fig3':'Clips wrong thermal-layer figure and swallows body text, not double-window.'}[x['id']]
 h.append(defect(x['path'],'figure',desc,'critical'))
for x in t['candidates'][2]['crops']:
 if x['id']=='p1-fig1': continue
 desc={'p1-sol-fig1':'Blank space and text, no wave diagram.','p1-sol-fig2':'Swallows scoring/body text and table edge.','p2-fig1':'Swallows constants, neighboring diagram and page number.','p2-fig2':'Clips moving particle, g_e label and velocity arrow.','p2-sol-fig1':'Clips z arrow/label and swallows body text.','p2-sol-fig2':'Clips top vectors F/B and swallows body text.','p3-fig1':'Swallows body text and clips bottom of heat-layer diagram.','p3-fig2':'Swallows body text and clips right wall edge.','p3-fig3':'Swallows body text and neighboring wall diagram.'}[x['id']]
 g.append(defect(x['path'],'figure',desc,'critical'))
for x in t['candidates'][1]['crops']:
 if x['id']=='p1-sol-fig2': continue
 desc={'p1-fig1':('Clips left fixed-wall hatching and axis.','major'),'p1-sol-fig1':('Clips y-axis label and arrow at top.','critical'),'p2-fig1':('Clips right ends of capacitor plates and bottom caption.','critical'),'p2-fig2':('Includes left fragments of neighboring capacitor and clipped caption.','minor'),'p2-fig3':('Cuts off top of cone and ellipse.','critical'),'p2-sol-fig1':('Includes extra score below the figure and small left-axis clipping; one score overlaps original drawing and cannot be removed by a rectangular crop.','minor'),'p2-sol-fig2':('Clips g_e and F label and swallows a sliver of prose below.','critical'),'p3-fig1':('Clips top of Δx label.','critical'),'p3-fig2':('Includes page number and adjacent score.','major'),'p3-fig3':('Swallows preceding problem text.','critical')}[x['id']]
 s.append(defect(x['path'],'figure',*desc))
decs={
'agent__haiku__for-zai__glm-5.3-flash.json':[(False,'This describes correct behavior; actual p1-fig1 is clean and complete, not a defect.'),(True,'Actual crop is blank/text instead of the wave diagram. Suggested box is not accepted.'),(True,'Actual crop includes table/scoring text; severity is critical by contract. Suggested box repeats original.'),(False,'No defect alleged, but claimed clean extraction is wrong: constants and neighboring figure are included.'),(False,'No defect alleged, but claimed completeness misses omitted particle, velocity and g_e label.'),(True,'Actual crop swallows prose and clips z; quoted sin(ωt) fragment is not present in this crop, but central allegation holds.'),(True,'Actual crop includes body text and clips upper vectors; source-embedded score alone is unavoidable, not the reason for failure.'),(True,'Body text above and clipped diagram bottom confirmed.'),(True,'Body text above confirmed; also clips right wall edge.'),(True,'Body text above and neighboring figure confirmed.')],
'zai__glm-5.3-flash__for-agent__haiku.json':[(True,'Printed separate scores are 2 and 2, not 6. Suggested aggregate 4 and total 10 are inferred; gold retains bullet scores and null aggregate.'),(True,'Printed separate scores are 3 and 1, not 2; gold retains bullet scores, null aggregate.'),(True,'Printed Като; garbled Бъд като is absent from source.'),(True,'Printed има and външна; systematic candidate changes confirmed.'),(True,'All specified scoring omissions confirmed.'),(True,'Formula operator and multiple textual corruptions confirmed; equation (7) is on solutions page 1, not page 2.'),(True,'Omissions and collapsed alternative solutions confirmed, but checker itself misreads product 2·4 as decimal 2,4; full numeric substitution is on solutions page 3, not page 4.'),(True,'Full formulas omitted as alleged; (13) is on solutions page 6, not page 5.'),(True,'Garbled final sentence and omitted equations (11)–(12) confirmed.'),(False,'Source clearly prints фундаменталин on problems page 2. Candidate faithfully preserves this printed typo.'),(True,'Table intrusion is real, but acceptable/full figure assertion is wrong: substantial body text is included and x label is clipped. Intended pointer is /problems/0/solution/figures/1, not problem 2; severity critical.')],
'zai__glm-5.3-flash__for-agent__sonnet.json':[(True,'Source огражда; candidate has an extra д.'),(False,'Informational layout relocation preserves complete hint content, not a transcription defect.'),(False,'Informational relocation, not missing content.'),(False,'Caption is stored separately; excluding it is acceptable. Checker misses clipping of the fixed-wall left edge.'),(True,'Actual crop includes full page number 3 and adjacent score. This is confirmed contamination, not merely a possibility; drawing itself is intact.')]
}
finish(t,d,c,{'agent__haiku.figs.view.json':h,'zai__glm-5.3-flash.figs.view.json':g,'agent__sonnet.figs.view.json':s},decs,'All three candidates fail. Sonnet preserves the mathematical content best and is the corrected base; Haiku omits substantial official derivations, while GLM omits hints and misreads a multiplication as a decimal. All 26 checker findings are adjudicated; several asserted clean crops are demonstrably defective and one checker wrongly rejects a printed typo.','All ten rendered pages (including blank problems page 4), all three full candidate views, all 29 actual candidate crops and all 26 checker findings inspected. Printed фундаменталин, дяната, воде, stray comma before q, lowercase m in equations (6)–(7), g versus g_e, decimal dots in the numerical table, and historical h=6,64×10^-34 are preserved. Two solution figures have scoring text interleaved with the original diagrams; tight rectangular crops necessarily retain the embedded scores. The page-3 cone hint also overlaps the preceding formula bounding rectangle, so its crop retains a small formula fragment at upper left; no figure content is clipped to hide this source-layout limitation. All eleven boxes corrected. No production content changed.')
