import json,datetime,copy
from pathlib import Path
id='nao-2023-ii-5-6'; task=json.load(open(f'tmp/bench/codex-resume/astronomy/{id}.task.json'));now=datetime.datetime.now(datetime.timezone.utc).isoformat();f=Path(task['out']);o=json.loads(f.read_text());backup=Path(f'tmp/bench/codex-resume/astronomy/{id}.interrupted-fable-draft.json')
if not backup.exists():backup.write_text(f.read_text())
base=task['candidates'][1];raw=json.load(open(base['view'].replace('.view.json','.json')))
o['tx']['reader']=raw['tx']['reader'];o['tx']['adjudicator']={'provider':'openai','model':'codex-gpt-6','promptVersion':'v1','at':now,'basedOn':[base['view']]}
o['tx']['notes']=o['tx']['notes'].split(' ADJUDICATOR (fable):')[0]+' Adjudicator openai:codex-gpt-6 resumed and independently reviewed all 11 rendered pages, all 33 available candidate crops, all candidate views and all 16 checker findings. Interrupted Fable draft retained as non-gold work product and corrected from source. Source typos Напиете (problems p.4) and рабира (solutions p.3) preserved. Decimal dots in 111.14, 2.22, 1852.3 and 1.4 are printed. Corrected boxes measured on pages; phase-table orientation and all six printed answer dates checked. Moon/cloud alt corrected: the Moon is in front of the cloud, precisely why picture Г is impossible.'
o['paper']['held']={'from':'2023-02-17','to':'2023-02-17'}
o['problems'][1]['figures'][3]['alt']='Жълт полумесец пред бял облак на тъмно нощно небе със звезди; долната дъга на полумесеца закрива облака.'
# Full panel crops, with numeric labels in caption only; no clipped pieces of caption in image.
for j,b in enumerate([[122,299,542,504],[552,299,877,504],[122,532,545,746],[559,532,868,746]]):o['problems'][0]['figures'][j]['tx']['bbox']=b
# Figure captions remain separate. Image/date matrix kept as a figure because image phases are the essential data.
o['problems'][2]['figures'][0]['tx']['bbox']=[113,70,812,892]
o['problems'][2]['solution']['figures'][1]['tx']['bbox']=[113,70,812,892]
# Printed panel number and task headings are retained structurally; all rubric lines remain verbatim.
def D(path,kind,description,severity='major'):return {'path':path,'kind':kind,'description':description,'severity':severity}
haiku=[D('/paper/totalPoints','points','60 is an inferred sum, never a printed total.'),D('/problems/0/statement','reworded','Printed пътешественици/возят/обяснете become пътешествия/възят/обосновете.'),D('/problems/2/statement','reworded','Printed се опитвате, лунен жител, По-нататък become се опитате, живей, По-натък.'),D('/problems/2/parts','reworded','когато becomes което and Вие се намирате becomes намираме.'),D('/problems/3/statement','reworded','Printed шахта becomes станция and свръхбързи becomes свръхбърз.'),D('/problems/3/parts/1/statement','wrong-value','One arcminute becomes един градус минута and дъгови минути becomes дълги минути.','critical'),D('/problems/4/parts','reworded','император becomes Spanish emperador; състави, годината and обикаля are corrupted.'),D('/problems/2/solution/figures','omission','Filled phase/date answer key on solutions p.7 omitted.','critical'),D('/problems','omission','Answer objects contain only kind:text with no printed final results extracted.')]
for i in range(5):haiku.append(D(f'/problems/{i}/solution/statement','reworded','Extensive visible prose corruption and/or missing sentences; p1 omits plate/helmet conclusion, p2 reverses cloud reasoning, p3 omits February5 and repeats incorrect phase, p4/p5 corrupt rubric verbs.','critical' if i<3 else 'major'))
for c in task['candidates'][0]['crops']:haiku.append(D(c['path'],'figure','Actual crop clips required content and/or captures unrelated text/figure; phase matrix cuts off top row, lunar orbit crop is almost entirely prose, butterfly crop is lunar astronauts.','critical'))
sonnet=[D('/problems/0/figures/2','figure','Crop cuts through printed numeral 3 at lower edge.','critical'),D('/problems/0/figures/3','figure','Crop cuts through printed numeral 4 at lower edge.','critical'),D('/problems/0/figures/1','figure','Right edge clips a narrow strip of the picture; border ends before complete panel.','minor'),D('/problems/1/figures','figure','All five crops include full printed caption lines also stored in caption; prompt requires captions outside crop.','minor'),D('/problems/1/figures/2/alt','reworded','Rabbit alt contains misspelled Заешче.','minor'),D('/problems/1/figures/3/alt','figure','Alt says Moon is behind cloud; actual picture shows crescent in front of cloud, which is the central impossible feature.'),D('/problems/2/parts/1/answer/value','pairing','Date pairings are individually correct but claimed left-to-right order is reversed for upright landscape table.'),D('/problems/2/solution/figures/1/alt','pairing','Claims reversed column sequence is left-to-right; upright source runs January26 through February17.'),D('/problems/3/figures','omission','Monarch illustration on problems p.2 absent; no quantities are lost.','minor')]
glm=[D('/problems/0/title','reworded','Printed неправилно becomes неправильно.'),D('/problems/0/statement','reworded','Printed своя becomes свой; title repeated with misspelling.'),D('/problems/0/solution/statement','reworded','сгъстен becomes съствен and printed обяда loses final а.'),D('/problems/0/solution/incomplete','metadata','Complete printed solution incorrectly marked incomplete with process note as reason.'),D('/problems/1/solution/statement','reworded','Printed сгъстен, излегнем and пръв become съствен, излегем and прв; printed typo рабира is silently corrected.'),D('/problems/1/figures','schema','Figure IDs use uppercase suffixes figA/figB/etc rather than valid lowercase slug/numeric convention.'),D('/problems/1/tx/sourceSpans','provenance','Problem2 statement begins on problems p.1, omitted from sourceSpans.'),D('/problems/2/statement','reworded','Printed подготвяте becomes подготовяте.'),D('/problems/2/figures/0/caption','reworded','Caption omits празните and corrupts правоъгълници; source typo Напиете silently corrected.'),D('/problems/2/parts/1/answer/value','wrong-value','Several Earth-photo dates do not match printed answer table: columns for February5/13/17 are mispaired.','critical'),D('/problems/2/solution/statement','omission','All three grading-criteria lines (2,2,8 points) are missing.'),D('/problems/2/solution/figures/0','figure','Actual lunar-orbit crop cuts first quarter, full moon and ray labels and includes grading prose.','critical'),D('/problems/3/figures/0','figure','Butterfly proposes page3 instead of actual page2; crop missing, and coordinates fall in blank region.','critical'),D('/problems/3/statement','reworded','недалечното becomes близкото; географска loses а.'),D('/problems/3/parts/1/statement','reworded','географска and дъгова/дъгови corrupted.'),D('/problems/3/solution/statement','reworded','Decimal dots replaced by commas; географска and пресмятане corrupted.'),D('/problems/3/tx/sourceSpans','provenance','Intro on problems p.2 omitted.'),D('/problems/4/statement','reworded','Printed денонощие becomes деноноще.')]
for j in range(4):glm.append(D(f'/problems/0/figures/{j}','figure','Top-row crops include a clipped body-text line; bottom-row crops cut off top strip of source pictures.','critical'))
for j in range(5):glm.append(D(f'/problems/1/figures/{j}','figure','Actual crop cuts caption letters and/or picture edge; lower panels also swallow following problem statement.','critical'))
findings=[]
for cf in task['checks']:
 ch=json.load(open(cf))
 for ix,d in enumerate(ch.get('defects',[])):
  tp=True;note='Confirmed by page images and candidate text; checker paths use one-based problem positions and must be shifted down by one to address the actual JSON.'
  if 'for-agent__sonnet' in cf:
   tp=False
   note=['Source really prints Напиете on problems p.4; reader correctly preserves the typo. The solution caption separately prints Напишете.','Informational confirmation of correctly preserved source typo рабира; not a candidate defect. Checker also names the wrong problem path and wrong missing letter.','Informational confirmation of individually correct date pairings, not a defect. It misses the reversed left-to-right claim; pointer should address problem3 rather than problem4.'][ix]
  elif 'agent__haiku__for-zai' in cf:
   note=['Missing crop confirmed, but file is not a mandatory reader-proposed field; root defect is wrong page3/bbox, whereas butterfly is on source problems p.2.','Confirmed: all four printed explanations are present; incomplete flag and reason are inappropriate.'][ix]
  elif ix==6:
   tp=False;note='Checker falsely claims butterfly is on problems p.3; it is on p.2. The candidate page2 is correct, but actual box targets unrelated astronaut pictures, a separate confirmed figure defect.'
  elif ix==3:note+=' Printed rubric says пресмятане, not the checker’s invented source typo престмяне.'
  elif ix==10:note='Actual illustration is a rabbit, not a unicorn. Alt mismatch confirmed (minor), despite informational severity in checker.'
  findings.append({'check':cf,'index':ix,'path':d['path'],'truePositive':tp,'note':note})
adj={'paperId':id,'at':now,'adjudicator':{'provider':'openai','model':'codex-gpt-6'},'basedOn':base['view'],'candidates':[{'view':c['view'],'candidateSha256':c['candidateSha256'],'defects':ds,'verdict':'fail'} for c,ds in zip(task['candidates'],[haiku,sonnet,glm])],'checkerFindings':findings,'escalations':[],'summary':'Sonnet is close to verbatim and provides the corrected base; its main failures are clipped figure labels and reversed description of phase-table column order. GLM has repeated spelling, answer-pairing and crop failures; Haiku extensively corrupts solutions. All11 source pages, all33 available candidate crops and all16 checker findings were independently reviewed; no source illegibility remains.'}
f.write_text(json.dumps(o,ensure_ascii=False,indent=2)+'\n');Path(task['adjudication']).write_text(json.dumps(adj,ensure_ascii=False,indent=2)+'\n')
